### ISSUE TITLE
/bin/sh: moses/moses/scripts/tokenizer/detokenizer.perl: No such file or directory

### ISSUE THREAD

**Issue by Picasso1503** [haryoa/stif-indonesia#6]
I have a problem when run in Terminal MACOS. 

I've been run this:
python -m stif_indonesia --exp-scenario supervised

But i'v got some error:
/bin/sh: moses/moses/bin/lmplz: No such file or directory
/bin/sh: moses/moses/bin/build_binary: No such file or directory
/bin/sh: moses/moses/scripts/tokenizer/detokenizer.perl: No such file or directory
/bin/sh: moses/moses/scripts/tokenizer/detokenizer.perl: No such file or directory

Anyone?
<img width="564" alt="Screen Shot 2020-11-20 at 23 42 20" src="https://user-images.githubusercontent.com/73958120/99825781-11db5480-2b8a-11eb-97db-6bdbdb91f756.png">

**Comment by haryoa** [comment]
Hello, actually if you run the code with Ubuntu, you should run this script to download MOSES (an SMT toolkit) binary files:

```
bash scripts/download_moses.sh
```

It will download the Ubuntu17.04 binary MOSES by itself. 

We tested our system on Ubuntu 18.04. Since you run it on MacOS, you need to download the Specific binary file macOS from here: 

```
http://www.statmt.org/moses/RELEASE-4.0/binaries/
```

Then unzip it and rename the folder (macOS) into `moses`

Make sure that the structure looks like this:
![image](https://user-images.githubusercontent.com/44270140/99868648-e2166600-2bf6-11eb-8e8a-42928c120ac6.png)

Beware though that we haven't tested it on MacOS, so we don't know if our script can run on MacOS.

**Comment by Picasso1503** [comment]
I've been downloaded the spesific binaries for macOS and Here are the error when i runned in macOS:

dyld: Library not loaded: /Users/hieu/workspace/xmlrpc-c/xmlrpc-c-1.39.07/lib/libxmlrpc_xmltok.3.39.dylib
  Referenced from: /Users/muhammadrizki/stif-indonesia/moses/moses/bin/lmplz
  Reason: image not found
/bin/sh: line 1: 24425 Abort trap: 6           moses/moses/bin/lmplz -S 20% -o 3 < data/labelled/train.for > output/supervised/lm/blm/data.arpa.for
dyld: Library not loaded: /Users/hieu/workspace/xmlrpc-c/xmlrpc-c-1.39.07/lib/libxmlrpc_xmltok.3.39.dylib
  Referenced from: /Users/muhammadrizki/stif-indonesia/moses/moses/bin/build_binary
  Reason: image not found

is it better If I run it on windows? have you tested it on windows before?

Thankyou and appriciate

**Comment by haryoa** [comment]
The error is caused by the compiled binary file on OSX, I don't know how to fix it :( . Would you mind to find the solution by yourself?

We also haven't tested it on windows. But you can run it on WSL-2 Windows (a bit slow).

We apologize for the inconvenience..
